Add metadata permissions
jhuapl-boss/boss pull request #107
Opened 2022-11-08 20:32 UTC by dxenes1

Permission modifications to separate resource and metadata permissions. 

Use cases:
1) Allow external collaborators to write metadata but not modify public spatial data.
2) Allow groups to manage metadata to update the website automatically.
3) Allow secondary analysis groups to access and write metadata for projects they are working with

Permission Groups

|               | read resource | add resource | update resource | delete resource | read metadata | add metadata | update metadata | delete metadata |
|---------------|---------------|--------------|-----------------|-----------------|---------------|--------------|-----------------|-----------------|
| read          |       x       |              |                 |                 |       x       |              |                 |                 |
| read+addmeta  |       x       |              |                 |                 |       x       |       x      |                 |                 |
| read+fullmeta |       x       |              |                 |                 |       x       |       x      |        x        |        x        |
| write         |       x       |       x      |        x        |                 |       x       |       x      |        x        |        x        |
| admin         |       x       |       x      |        x        |                 |       x       |       x      |        x        |        x        |
| admin+delete  |       x       |       x      |        x        |        x        |       x       |       x      |        x        |        x        |

2022-11-08 21:58 UTC, movestill requested changes

2022-11-08 21:58 UTC, movestill commented on django/bosscore/models.py
> +            ('update_metadata', 'Can read metadata for the channel'),
The description is incorrect for all instances of `update_metadata`.

2022-11-08 21:58 UTC, movestill commented on django/bosscore/permissions.py
> +        # dev note: with the addition of metadata permissions this function is no longer used
If this is the case, let's remove the method.

2022-11-08 21:58 UTC, movestill commented on django/mgmt/utils.py
>      def make_selection(p,is_chan):
I know you didn't write this, but can you document what `p` is for future readers?

2022-12-22 21:07 UTC, dxenes1 commented
I think all requested changes should be addressed in the latest commit, but please let me know if I missed anything!

2023-01-03 13:42 UTC, movestill approved these changes, later dismissed
I see lots of old code that could use refactoring, but I think your changes for metadata look good!

2025-11-26 16:16 UTC, dxenes1 commented
Since we now use a separate metadata service and not the BossDB metadata API, I'm closing this

2025-11-26 16:16 UTC, closed without merging